/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hf' at '3/10/15 6:44 PM' with Gradle 2.2.1
 *
 * @author hf, @date 3/10/15 6:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
